language: objective-c
osx_image: xcode8
xcode_workspace: push-sdk.xcworkspace
xcode_scheme: push-sdk
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
    - 1.x_dev

script:
  - xcodebuild -workspace push-sdk.xcworkspace -scheme push-sdk -sdk iphonesimulator build
  - xcodebuild -workspace push-sdk.xcworkspace -scheme push-sdk -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' test